# Generated by Django 2.2.19 on 2023-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230312_1658'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='basket',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Пользователь не может добавить рецепт в Корзину дважды'),
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='Пользователь не может добавить рецепт в Избранное дважды'),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipe',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='Связь ингредиента и рецепта должна быть уникальна'),
        ),
        migrations.AddConstraint(
            model_name='tagrecipe',
            constraint=models.UniqueConstraint(fields=('tag', 'recipe'), name='Связь между тегом и рецептом должна быть уникальна'),
        ),
    ]
