# Generated by Django 2.2.19 on 2023-03-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230317_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Укажите наименование ингредиента', max_length=200, unique=True, verbose_name='Наименование ингредиента'),
        ),
    ]
