# Generated by Django 2.2.19 on 2023-03-16 21:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230313_1948'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cannot_follow_yourself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Укажите пароль', max_length=150, verbose_name='Пароль'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='Пользователь не может подписаться сам на себя'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Пользователь не может подписаться на другого пользователя дважды'),
        ),
    ]
